import './globals.css';
import type { Metadata } from 'next';
import { Header, Footer } from '../../components';
import { StateContext } from '../../components/context/StateContext';
import { toast } from 'ract-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <StateContext>
          <Header />
          <main className="main-container">{children}</main>
          <Footer />
        </StateContext>
      </body>
    </html>
  );
}
